resources/views/

    ajaxinfo.blade.php
    mailer.blade.php
    shell.blade.php
    leads.blade.php
    premium.blade.php
    addBalance.blade.php
    divPage1.blade.php
    settingEdit.blade.php
    tticket.blade.php
    treport.blade.php
    funds.blade.php
    addBalanceAction.blade.php
    rdp.blade.php
    tutorial.blade.php
    pay.blade.php
    btc3.blade.php
    banks.blade.php
    pm3.blade.php
    tickets.blade.php
    becomeseller.blade.php
    scampage.blade.php
    logout.blade.php
    active.blade.php
    orders.blade.php
    setting.blade.php
    static.blade.php
    smtp.blade.php
    addt.blade.php
    cPanel.blade.php
    checkEmailChange.blade.php
    reports.blade.php
    shoprules.blade.php
    profile.blade.php
    addc.blade.php
    vt.blade.php
    vr.blade.php
    divPageticket.blade.php
    divPagereport.blade.php
    showTicket.blade.php
    check2shell.blade.php
    check2smtp.blade.php
    check2cp.blade.php
    check2mailer.blade.php
    openorder.blade.php
    addReply.blade.php
    addReportReply.blade.php
    divPagepayment.blade.php
    check.blade.php
    PMcheck.blade.php
    payment.blade.php